// <auto-generated />
using AudioSnapServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioSnapServer.Migrations
{
    [DbContext(typeof(AudioSnapDbContext))]
    partial class AudioSnapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AudioSnapServer.Models.ResponseStorage.AcoustIDStorage", b =>
                {
                    b.Property<string>("AcoustID")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("acoustid");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint")
                        .HasColumnName("duration");

                    b.Property<uint>("Hash")
                        .HasColumnType("int unsigned")
                        .HasColumnName("hash");

                    b.Property<double>("MatchingScore")
                        .HasColumnType("double")
                        .HasColumnName("score");

                    b.Property<string>("RecordingID")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("recording_id");

                    b.HasKey("AcoustID");

                    b.ToTable("AcoustIDs");
                });

            modelBuilder.Entity("AudioSnapServer.Models.ResponseStorage.RecordingStorage", b =>
                {
                    b.Property<string>("RecordingID")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("recording_id");

                    b.Property<string>("RecordingResponse")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("recording_response");

                    b.HasKey("RecordingID");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("AudioSnapServer.Models.ResponseStorage.ReleaseStorage", b =>
                {
                    b.Property<string>("ReleaseID")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("release_id");

                    b.Property<string>("CoverResponse")
                        .HasColumnType("longtext")
                        .HasColumnName("cover-response");

                    b.Property<string>("ReleaseResponse")
                        .HasColumnType("longtext")
                        .HasColumnName("release_response");

                    b.HasKey("ReleaseID");

                    b.ToTable("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
